#Model Parameters
z_dim: 32
s_dim: 0
eta_dim: 8
rsample: "sample_uniform"
nhidden: 256
layers: 2
pad_val: -500

#Training Parameters
dataset: "commaTraj"
learning_rate: 0.0002
batch_size: 256
epochs: 2000
dis_coef: 0.2
fat_thres: 1
lsgan: False
lambda: 1
use_logger: True

#Procedure
load_model: False
run_training: True
run_inf: False
save_output: True