#Model Parameters
z_dim: 24
s_dim: 4
eta_dim: 5
rsample: "sample_uniform"
nhidden: 256
layers: 2
pad_val: -2

#Training Parameters
dataset: "radar"
learning_rate: 0.0001
batch_size: 128
epochs: 1000
dis_coef: 0.01
fat_thres: 50
lsgan: True
lambda: 0.01
use_logger: True

#Procedure
load_model: True
run_training: True
run_inf: False
save_output: True