#Model Parameters
z_dim: 10
s_dim: 0
eta_dim: 4
rsample: "sample_uniform"
nhidden: 100
layers: 1
pad_val: -2

#Training Parameters
dataset: "metro"
learning_rate: 0.001
batch_size: 128
epochs: 2000
dis_coef: 2
fat_thres: 0.1
lsgan: True
lambda: 10
use_logger: True

#Procedure
